<?xml version="1.0" encoding="utf-8"?>
    <Project ToolsVersion="4.0" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
      <ImportGroup Label="PropertySheets" />
      <PropertyGroup Label="UserMacros" />
      <PropertyGroup>
        <IncludePath>$(ProjectDir)ThirdParty\include;$(IncludePath)</IncludePath>
        <LibraryPath>$(ProjectDir)ThirdParty\lib;$(LibraryPath)</LibraryPath>
        <OutDir>$(ProjectDir)Build\Binaries\$(Configuration)\</OutDir>
        <IntDir>$(ProjectDir)Intermediate\$(Configuration)\</IntDir>
      </PropertyGroup>
      <ItemDefinitionGroup>
        <ClCompile>
          <PreprocessorDefinitions>REFLECTION_ENABLED;%(PreprocessorDefinitions)</PreprocessorDefinitions>
        </ClCompile>
      </ItemDefinitionGroup>
      <ItemGroup />
      <ImportGroup Label="ExtensionTargets" />
    </Project>